-- Create Bronze schema if not exists
CREATE SCHEMA IF NOT EXISTS bronze;

-- Create Airbnb raw table in Bronze schema
CREATE TABLE IF NOT EXISTS bronze.airbnb_raw (
    listing_id BIGINT,
    scrape_id BIGINT,
    scraped_date DATE,
    host_id BIGINT,
    host_name TEXT,
    host_since DATE,
    host_is_superhost BOOLEAN,
    host_neighbourhood TEXT,
    listing_neighbourhood TEXT,
    property_type TEXT,
    room_type TEXT,
    accommodates INT,
    price NUMERIC,
    has_availability BOOLEAN,
    availability_30 INT,
    number_of_reviews INT,
    review_scores_rating NUMERIC,
    review_scores_accuracy NUMERIC,
    review_scores_cleanliness NUMERIC,
    review_scores_checkin NUMERIC,
    review_scores_communication NUMERIC,
    review_scores_value NUMERIC
);

SELECT * FROM bronze.airbnb_raw;
-- Create Census G01 raw table in Bronze schema
CREATE TABLE IF NOT EXISTS bronze.census_g01 (
    lga_code_2016 TEXT,
    tot_p_m NUMERIC,
    tot_p_f NUMERIC,
    tot_p_p NUMERIC,
    age_0_4_yr_m NUMERIC,
    age_0_4_yr_f NUMERIC,
    age_0_4_yr_p NUMERIC,
    age_5_14_yr_m NUMERIC,
    age_5_14_yr_f NUMERIC,
    age_5_14_yr_p NUMERIC,
    age_15_19_yr_m NUMERIC,
    age_15_19_yr_f NUMERIC,
    age_15_19_yr_p NUMERIC,
    age_20_24_yr_m NUMERIC,
    age_20_24_yr_f NUMERIC,
    age_20_24_yr_p NUMERIC,
    age_25_34_yr_m NUMERIC,
    age_25_34_yr_f NUMERIC,
    age_25_34_yr_p NUMERIC,
    age_35_44_yr_m NUMERIC,
    age_35_44_yr_f NUMERIC,
    age_35_44_yr_p NUMERIC,
    age_45_54_yr_m NUMERIC,
    age_45_54_yr_f NUMERIC,
    age_45_54_yr_p NUMERIC,
    age_55_64_yr_m NUMERIC,
    age_55_64_yr_f NUMERIC,
    age_55_64_yr_p NUMERIC,
    age_65_74_yr_m NUMERIC,
    age_65_74_yr_f NUMERIC,
    age_65_74_yr_p NUMERIC,
    age_75_84_yr_m NUMERIC,
    age_75_84_yr_f NUMERIC,
    age_75_84_yr_p NUMERIC,
    age_85ov_m NUMERIC,
    age_85ov_f NUMERIC,
    age_85ov_p NUMERIC,
    counted_census_night_home_m NUMERIC,
    counted_census_night_home_f NUMERIC,
    counted_census_night_home_p NUMERIC,
    count_census_nt_ewhere_aust_m NUMERIC,
    count_census_nt_ewhere_aust_f NUMERIC,
    count_census_nt_ewhere_aust_p NUMERIC,
    indigenous_psns_aboriginal_m NUMERIC,
    indigenous_psns_aboriginal_f NUMERIC,
    indigenous_psns_aboriginal_p NUMERIC,
    indig_psns_torres_strait_is_m NUMERIC,
    indig_psns_torres_strait_is_f NUMERIC,
    indig_psns_torres_strait_is_p NUMERIC,
    indig_bth_abor_torres_st_is_m NUMERIC,
    indig_bth_abor_torres_st_is_f NUMERIC,
    indig_bth_abor_torres_st_is_p NUMERIC,
    indigenous_p_tot_m NUMERIC,
    indigenous_p_tot_f NUMERIC,
    indigenous_p_tot_p NUMERIC,
    birthplace_australia_m NUMERIC,
    birthplace_australia_f NUMERIC,
    birthplace_australia_p NUMERIC,
    birthplace_elsewhere_m NUMERIC,
    birthplace_elsewhere_f NUMERIC,
    birthplace_elsewhere_p NUMERIC,
    lang_spoken_home_eng_only_m NUMERIC,
    lang_spoken_home_eng_only_f NUMERIC,
    lang_spoken_home_eng_only_p NUMERIC,
    lang_spoken_home_oth_lang_m NUMERIC,
    lang_spoken_home_oth_lang_f NUMERIC,
    lang_spoken_home_oth_lang_p NUMERIC,
    australian_citizen_m NUMERIC,
    australian_citizen_f NUMERIC,
    australian_citizen_p NUMERIC,
    age_psns_att_educ_inst_0_4_m NUMERIC,
    age_psns_att_educ_inst_0_4_f NUMERIC,
    age_psns_att_educ_inst_0_4_p NUMERIC,
    age_psns_att_educ_inst_5_14_m NUMERIC,
    age_psns_att_educ_inst_5_14_f NUMERIC,
    age_psns_att_educ_inst_5_14_p NUMERIC,
    age_psns_att_edu_inst_15_19_m NUMERIC,
    age_psns_att_edu_inst_15_19_f NUMERIC,
    age_psns_att_edu_inst_15_19_p NUMERIC,
    age_psns_att_edu_inst_20_24_m NUMERIC,
    age_psns_att_edu_inst_20_24_f NUMERIC,
    age_psns_att_edu_inst_20_24_p NUMERIC,
    age_psns_att_edu_inst_25_ov_m NUMERIC,
    age_psns_att_edu_inst_25_ov_f NUMERIC,
    age_psns_att_edu_inst_25_ov_p NUMERIC,
    high_yr_schl_comp_yr_12_eq_m NUMERIC,
    high_yr_schl_comp_yr_12_eq_f NUMERIC,
    high_yr_schl_comp_yr_12_eq_p NUMERIC,
    high_yr_schl_comp_yr_11_eq_m NUMERIC,
    high_yr_schl_comp_yr_11_eq_f NUMERIC,
    high_yr_schl_comp_yr_11_eq_p NUMERIC,
    high_yr_schl_comp_yr_10_eq_m NUMERIC,
    high_yr_schl_comp_yr_10_eq_f NUMERIC,
    high_yr_schl_comp_yr_10_eq_p NUMERIC,
    high_yr_schl_comp_yr_9_eq_m NUMERIC,
    high_yr_schl_comp_yr_9_eq_f NUMERIC,
    high_yr_schl_comp_yr_9_eq_p NUMERIC,
    high_yr_schl_comp_yr_8_belw_m NUMERIC,
    high_yr_schl_comp_yr_8_belw_f NUMERIC,
    high_yr_schl_comp_yr_8_belw_p NUMERIC,
    high_yr_schl_comp_d_n_g_sch_m NUMERIC,
    high_yr_schl_comp_d_n_g_sch_f NUMERIC,
    high_yr_schl_comp_d_n_g_sch_p NUMERIC,
    count_psns_occ_priv_dwgs_m NUMERIC,
    count_psns_occ_priv_dwgs_f NUMERIC,
    count_psns_occ_priv_dwgs_p NUMERIC,
    count_persons_other_dwgs_m NUMERIC,
    count_persons_other_dwgs_f NUMERIC,
    count_persons_other_dwgs_p NUMERIC
);
select * from  bronze.census_g01; 

CREATE TABLE IF NOT EXISTS bronze.census_g02 (
    lga_code_2016 TEXT,
    median_age_persons NUMERIC,
    median_mortgage_repay_monthly NUMERIC,
    median_tot_prsnl_inc_weekly NUMERIC,
    median_rent_weekly NUMERIC,
    median_tot_fam_inc_weekly NUMERIC,
    average_num_psns_per_bedroom NUMERIC,
    median_tot_hhd_inc_weekly NUMERIC,
    average_household_size NUMERIC
);

select * from  bronze.census_g02; 

CREATE TABLE IF NOT EXISTS bronze.lga_codes (
    lga_code TEXT PRIMARY KEY,
    lga_name TEXT
);
select * from  bronze.lga_codes; 


CREATE TABLE IF NOT EXISTS bronze.lga_suburb_mapping (
    suburb_name TEXT,
    lga_name TEXT 
);

